name: miel_work_web
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluent_ui: ^4.8.6
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  modal_bottom_sheet: ^2.1.2
  http: ^1.2.0
  flutter_spinkit: ^5.2.0
  syncfusion_flutter_datagrid_export: ^25.2.4
  syncfusion_localizations: ^25.2.4
  syncfusion_flutter_calendar: ^25.2.4
  file_picker: ^6.1.1
  file_selector: ^1.0.3
  pdf: ^3.10.8
  universal_html: ^2.2.4
  common_utils: ^2.1.0
  multiple_stream_builder: ^3.0.2
  url_launcher: ^6.2.5
  currency_text_input_formatter: ^2.2.3
  board_datetime_picker: ^1.4.0
  flutter_colorpicker: ^1.0.3
  calendar_date_picker2: ^0.5.5
  webkul_textfield_with_label: ^0.0.5

  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  firebase_messaging: ^14.9.2
  flutter_local_notifications: ^17.1.2

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: master  # or 786d04363f587b818ce585d25b9c2bb62de95aba

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: SourceHanSansJP-Bold
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Bold.otf
    - family: SourceHanSansJP-Regular
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Regular.otf