name: miel_work_web
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  page_transition: ^2.1.0
  modal_bottom_sheet: ^3.0.0
  alert_banner: ^1.0.1
  http: ^1.2.1
  flutter_spinkit: ^5.2.1
  syncfusion_flutter_datagrid_export: ^26.1.39
  syncfusion_localizations: ^26.1.39
  file_picker: ^8.0.5
  file_selector: ^1.0.3
  pdf: ^3.10.8
  universal_html: ^2.2.4
  common_utils: ^2.1.0
  multiple_stream_builder: ^3.0.2
  scroll_to_index: ^3.0.1
  url_launcher: ^6.3.0
  currency_text_input_formatter: ^2.2.3
  board_datetime_picker: ^1.6.8
  flutter_colorpicker: ^1.1.0
  calendar_date_picker2: ^1.1.5
  month_picker_dialog: ^4.0.0
  webkul_textfield_with_label: ^0.0.5
  signature: ^5.5.0
  calendar_view: ^1.2.0

  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2

dependency_overrides:
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: master  # or 786d04363f587b818ce585d25b9c2bb62de95aba

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: SourceHanSansJP-Bold
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Bold.otf
    - family: SourceHanSansJP-Regular
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Regular.otf