import 'package:flutter/material.dart';
import 'package:miel_work_web/models/organization.dart';
import 'package:miel_work_web/models/report.dart';
import 'package:miel_work_web/models/user.dart';
import 'package:miel_work_web/services/report.dart';

class ReportProvider with ChangeNotifier {
  final ReportService _reportService = ReportService();

  Future<String?> create({
    required OrganizationModel? organization,
    required DateTime createdAt,
    required String workUser1Name,
    required String workUser1Time,
    required String workUser2Name,
    required String workUser2Time,
    required String workUser3Name,
    required String workUser3Time,
    required String workUser4Name,
    required String workUser4Time,
    required String workUser5Name,
    required String workUser5Time,
    required String workUser6Name,
    required String workUser6Time,
    required String workUser7Name,
    required String workUser7Time,
    required String workUser8Name,
    required String workUser8Time,
    required String workUser9Name,
    required String workUser9Time,
    required String workUser10Name,
    required String workUser10Time,
    required String workUser11Name,
    required String workUser11Time,
    required String workUser12Name,
    required String workUser12Time,
    required String workUser13Name,
    required String workUser13Time,
    required String workUser14Name,
    required String workUser14Time,
    required String workUser15Name,
    required String workUser15Time,
    required String workUser16Name,
    required String workUser16Time,
    required String visitCount1_12,
    required String visitCount1_20,
    required String visitCount1_22,
    required String visitCount2_12,
    required String visitCount2_20,
    required String visitCount2_22,
    required String visitCount3_12,
    required String visitCount3_20,
    required String visitCount3_22,
    required String visitCount4_12,
    required String visitCount4_20,
    required String visitCount4_22,
    required String visitCount5_12,
    required String visitCount5_20,
    required String visitCount5_22,
    required String visitCount6_12,
    required String visitCount6_20,
    required String visitCount6_22,
    required String lockerUse,
    required String lockerLost,
    required String lockerRecovery,
    required String event1,
    required String event2,
    required String marketing,
    required String interview,
    required String openSquare,
    required String openSquareFee,
    required String openSquareStatus,
    required String meeting,
    required String mailCheck10Name,
    required String mailCheck10Status,
    required String mailCheck12Name,
    required String mailCheck12Status,
    required String mailCheck18Name,
    required String mailCheck18Status,
    required String mailCheck22Name,
    required String mailCheck22Status,
    required String warning19Status,
    required String warning19Deal,
    required String warning23Status,
    required String warning23Deal,
    required String advance1,
    required String advance2,
    required String advance3,
    required String repair,
    required String repairStatus,
    required String repairDeal,
    required String problem,
    required String problemDeal,
    required String pamphlet1Status,
    required String pamphlet1Name,
    required String pamphlet1Fee,
    required String pamphlet2Status,
    required String pamphlet2Name,
    required String pamphlet2Fee,
    required String pamphlet3Status,
    required String pamphlet3Name,
    required String pamphlet3Fee,
    required String pamphlet4Status,
    required String pamphlet4Name,
    required String pamphlet4Fee,
    required String pamphlet5Status,
    required String pamphlet5Name,
    required String pamphlet5Fee,
    required String pamphlet6Status,
    required String pamphlet6Name,
    required String pamphlet6Fee,
    required String pamphlet7Status,
    required String pamphlet7Name,
    required String pamphlet7Fee,
    required String equipment1Type,
    required String equipment1Name,
    required String equipment1Vendor,
    required String equipment1Delivery,
    required String equipment1Client,
    required String equipment2Type,
    required String equipment2Name,
    required String equipment2Vendor,
    required String equipment2Delivery,
    required String equipment2Client,
    required String equipment3Type,
    required String equipment3Name,
    required String equipment3Vendor,
    required String equipment3Delivery,
    required String equipment3Client,
    required String equipment4Type,
    required String equipment4Name,
    required String equipment4Vendor,
    required String equipment4Delivery,
    required String equipment4Client,
    required String equipment5Type,
    required String equipment5Name,
    required String equipment5Vendor,
    required String equipment5Delivery,
    required String equipment5Client,
    required String equipment6Type,
    required String equipment6Name,
    required String equipment6Vendor,
    required String equipment6Delivery,
    required String equipment6Client,
    required String contact,
    required String lastConfirm,
    required String agenda,
    required String confirm1,
    required String confirm2,
    required String confirm3,
    required String confirm4,
    required String confirm5,
    required String confirm6,
    required String confirm7,
    required String confirm8,
    required String confirm9,
    required String confirm10,
    required String confirm11,
    required String confirm12,
    required String passport,
    required String passportCount1,
    required String passportCount2,
    required String passportCount3,
    required UserModel? loginUser,
  }) async {
    String? error;
    if (organization == null) return '日報の保存に失敗しました';
    if (loginUser == null) return '日報の保存に失敗しました';
    try {
      String id = _reportService.id();
      _reportService.create({
        'id': id,
        'organizationId': organization.id,
        'workUser1Name': workUser1Name,
        'workUser1Time': workUser1Time,
        'workUser2Name': workUser2Name,
        'workUser2Time': workUser2Time,
        'workUser3Name': workUser3Name,
        'workUser3Time': workUser3Time,
        'workUser4Name': workUser4Name,
        'workUser4Time': workUser4Time,
        'workUser5Name': workUser5Name,
        'workUser5Time': workUser5Time,
        'workUser6Name': workUser6Name,
        'workUser6Time': workUser6Time,
        'workUser7Name': workUser7Name,
        'workUser7Time': workUser7Time,
        'workUser8Name': workUser8Name,
        'workUser8Time': workUser8Time,
        'workUser9Name': workUser9Name,
        'workUser9Time': workUser9Time,
        'workUser10Name': workUser10Name,
        'workUser10Time': workUser10Time,
        'workUser11Name': workUser11Name,
        'workUser11Time': workUser11Time,
        'workUser12Name': workUser12Name,
        'workUser12Time': workUser12Time,
        'workUser13Name': workUser13Name,
        'workUser13Time': workUser13Time,
        'workUser14Name': workUser14Name,
        'workUser14Time': workUser14Time,
        'workUser15Name': workUser15Name,
        'workUser15Time': workUser15Time,
        'workUser16Name': workUser16Name,
        'workUser16Time': workUser16Time,
        'visitCount1_12': visitCount1_12,
        'visitCount1_20': visitCount1_20,
        'visitCount1_22': visitCount1_22,
        'visitCount2_12': visitCount2_12,
        'visitCount2_20': visitCount2_20,
        'visitCount2_22': visitCount2_22,
        'visitCount3_12': visitCount3_12,
        'visitCount3_20': visitCount3_20,
        'visitCount3_22': visitCount3_22,
        'visitCount4_12': visitCount4_12,
        'visitCount4_20': visitCount4_20,
        'visitCount4_22': visitCount4_22,
        'visitCount5_12': visitCount5_12,
        'visitCount5_20': visitCount5_20,
        'visitCount5_22': visitCount5_22,
        'visitCount6_12': visitCount6_12,
        'visitCount6_20': visitCount6_20,
        'visitCount6_22': visitCount6_22,
        'lockerUse': lockerUse,
        'lockerLost': lockerLost,
        'lockerRecovery': lockerRecovery,
        'event1': event1,
        'event2': event2,
        'marketing': marketing,
        'interview': interview,
        'openSquare': openSquare,
        'openSquareFee': openSquareFee,
        'openSquareStatus': openSquareStatus,
        'meeting': meeting,
        'mailCheck10Name': mailCheck10Name,
        'mailCheck10Status': mailCheck10Status,
        'mailCheck12Name': mailCheck12Name,
        'mailCheck12Status': mailCheck12Status,
        'mailCheck18Name': mailCheck18Name,
        'mailCheck18Status': mailCheck18Status,
        'mailCheck22Name': mailCheck22Name,
        'mailCheck22Status': mailCheck22Status,
        'warning19Status': warning19Status,
        'warning19Deal': warning19Deal,
        'warning23Status': warning23Status,
        'warning23Deal': warning23Deal,
        'advance1': advance1,
        'advance2': advance2,
        'advance3': advance3,
        'repair': repair,
        'repairStatus': repairStatus,
        'repairDeal': repairDeal,
        'problem': problem,
        'problemDeal': problemDeal,
        'pamphlet1Status': pamphlet1Status,
        'pamphlet1Name': pamphlet1Name,
        'pamphlet1Fee': pamphlet1Fee,
        'pamphlet2Status': pamphlet2Status,
        'pamphlet2Name': pamphlet2Name,
        'pamphlet2Fee': pamphlet2Fee,
        'pamphlet3Status': pamphlet3Status,
        'pamphlet3Name': pamphlet3Name,
        'pamphlet3Fee': pamphlet3Fee,
        'pamphlet4Status': pamphlet4Status,
        'pamphlet4Name': pamphlet4Name,
        'pamphlet4Fee': pamphlet4Fee,
        'pamphlet5Status': pamphlet5Status,
        'pamphlet5Name': pamphlet5Name,
        'pamphlet5Fee': pamphlet5Fee,
        'pamphlet6Status': pamphlet6Status,
        'pamphlet6Name': pamphlet6Name,
        'pamphlet6Fee': pamphlet6Fee,
        'pamphlet7Status': pamphlet7Status,
        'pamphlet7Name': pamphlet7Name,
        'pamphlet7Fee': pamphlet7Fee,
        'equipment1Type': equipment1Type,
        'equipment1Name': equipment1Name,
        'equipment1Vendor': equipment1Vendor,
        'equipment1Delivery': equipment1Delivery,
        'equipment1Client': equipment1Client,
        'equipment2Type': equipment2Type,
        'equipment2Name': equipment2Name,
        'equipment2Vendor': equipment2Vendor,
        'equipment2Delivery': equipment2Delivery,
        'equipment2Client': equipment2Client,
        'equipment3Type': equipment3Type,
        'equipment3Name': equipment3Name,
        'equipment3Vendor': equipment3Vendor,
        'equipment3Delivery': equipment3Delivery,
        'equipment3Client': equipment3Client,
        'equipment4Type': equipment4Type,
        'equipment4Name': equipment4Name,
        'equipment4Vendor': equipment4Vendor,
        'equipment4Delivery': equipment4Delivery,
        'equipment4Client': equipment4Client,
        'equipment5Type': equipment5Type,
        'equipment5Name': equipment5Name,
        'equipment5Vendor': equipment5Vendor,
        'equipment5Delivery': equipment5Delivery,
        'equipment5Client': equipment5Client,
        'equipment6Type': equipment6Type,
        'equipment6Name': equipment6Name,
        'equipment6Vendor': equipment6Vendor,
        'equipment6Delivery': equipment6Delivery,
        'equipment6Client': equipment6Client,
        'contact': contact,
        'lastConfirm': lastConfirm,
        'agenda': agenda,
        'confirm1': confirm1,
        'confirm2': confirm2,
        'confirm3': confirm3,
        'confirm4': confirm4,
        'confirm5': confirm5,
        'confirm6': confirm6,
        'confirm7': confirm7,
        'confirm8': confirm8,
        'confirm9': confirm9,
        'confirm10': confirm10,
        'confirm11': confirm11,
        'confirm12': confirm12,
        'passport': passport,
        'passportCount1': passportCount1,
        'passportCount2': passportCount2,
        'passportCount3': passportCount3,
        'approval': 0,
        'createdUserId': loginUser.id,
        'createdUserName': loginUser.name,
        'createdAt': createdAt,
        'expirationAt': createdAt.add(const Duration(days: 365)),
      });
    } catch (e) {
      error = '日報の保存に失敗しました';
    }
    return error;
  }

  Future<String?> update({
    required ReportModel report,
    required String workUser1Name,
    required String workUser1Time,
    required String workUser2Name,
    required String workUser2Time,
    required String workUser3Name,
    required String workUser3Time,
    required String workUser4Name,
    required String workUser4Time,
    required String workUser5Name,
    required String workUser5Time,
    required String workUser6Name,
    required String workUser6Time,
    required String workUser7Name,
    required String workUser7Time,
    required String workUser8Name,
    required String workUser8Time,
    required String workUser9Name,
    required String workUser9Time,
    required String workUser10Name,
    required String workUser10Time,
    required String workUser11Name,
    required String workUser11Time,
    required String workUser12Name,
    required String workUser12Time,
    required String workUser13Name,
    required String workUser13Time,
    required String workUser14Name,
    required String workUser14Time,
    required String workUser15Name,
    required String workUser15Time,
    required String workUser16Name,
    required String workUser16Time,
    required String visitCount1_12,
    required String visitCount1_20,
    required String visitCount1_22,
    required String visitCount2_12,
    required String visitCount2_20,
    required String visitCount2_22,
    required String visitCount3_12,
    required String visitCount3_20,
    required String visitCount3_22,
    required String visitCount4_12,
    required String visitCount4_20,
    required String visitCount4_22,
    required String visitCount5_12,
    required String visitCount5_20,
    required String visitCount5_22,
    required String visitCount6_12,
    required String visitCount6_20,
    required String visitCount6_22,
    required String lockerUse,
    required String lockerLost,
    required String lockerRecovery,
    required String event1,
    required String event2,
    required String marketing,
    required String interview,
    required String openSquare,
    required String openSquareFee,
    required String openSquareStatus,
    required String meeting,
    required String mailCheck10Name,
    required String mailCheck10Status,
    required String mailCheck12Name,
    required String mailCheck12Status,
    required String mailCheck18Name,
    required String mailCheck18Status,
    required String mailCheck22Name,
    required String mailCheck22Status,
    required String warning19Status,
    required String warning19Deal,
    required String warning23Status,
    required String warning23Deal,
    required String advance1,
    required String advance2,
    required String advance3,
    required String repair,
    required String repairStatus,
    required String repairDeal,
    required String problem,
    required String problemDeal,
    required String pamphlet1Status,
    required String pamphlet1Name,
    required String pamphlet1Fee,
    required String pamphlet2Status,
    required String pamphlet2Name,
    required String pamphlet2Fee,
    required String pamphlet3Status,
    required String pamphlet3Name,
    required String pamphlet3Fee,
    required String pamphlet4Status,
    required String pamphlet4Name,
    required String pamphlet4Fee,
    required String pamphlet5Status,
    required String pamphlet5Name,
    required String pamphlet5Fee,
    required String pamphlet6Status,
    required String pamphlet6Name,
    required String pamphlet6Fee,
    required String pamphlet7Status,
    required String pamphlet7Name,
    required String pamphlet7Fee,
    required String equipment1Type,
    required String equipment1Name,
    required String equipment1Vendor,
    required String equipment1Delivery,
    required String equipment1Client,
    required String equipment2Type,
    required String equipment2Name,
    required String equipment2Vendor,
    required String equipment2Delivery,
    required String equipment2Client,
    required String equipment3Type,
    required String equipment3Name,
    required String equipment3Vendor,
    required String equipment3Delivery,
    required String equipment3Client,
    required String equipment4Type,
    required String equipment4Name,
    required String equipment4Vendor,
    required String equipment4Delivery,
    required String equipment4Client,
    required String equipment5Type,
    required String equipment5Name,
    required String equipment5Vendor,
    required String equipment5Delivery,
    required String equipment5Client,
    required String equipment6Type,
    required String equipment6Name,
    required String equipment6Vendor,
    required String equipment6Delivery,
    required String equipment6Client,
    required String contact,
    required String lastConfirm,
    required String agenda,
    required String confirm1,
    required String confirm2,
    required String confirm3,
    required String confirm4,
    required String confirm5,
    required String confirm6,
    required String confirm7,
    required String confirm8,
    required String confirm9,
    required String confirm10,
    required String confirm11,
    required String confirm12,
    required String passport,
    required String passportCount1,
    required String passportCount2,
    required String passportCount3,
    required UserModel? loginUser,
  }) async {
    String? error;
    if (loginUser == null) return '日報の保存に失敗しました';
    try {
      _reportService.update({
        'id': report.id,
        'workUser1Name': workUser1Name,
        'workUser1Time': workUser1Time,
        'workUser2Name': workUser2Name,
        'workUser2Time': workUser2Time,
        'workUser3Name': workUser3Name,
        'workUser3Time': workUser3Time,
        'workUser4Name': workUser4Name,
        'workUser4Time': workUser4Time,
        'workUser5Name': workUser5Name,
        'workUser5Time': workUser5Time,
        'workUser6Name': workUser6Name,
        'workUser6Time': workUser6Time,
        'workUser7Name': workUser7Name,
        'workUser7Time': workUser7Time,
        'workUser8Name': workUser8Name,
        'workUser8Time': workUser8Time,
        'workUser9Name': workUser9Name,
        'workUser9Time': workUser9Time,
        'workUser10Name': workUser10Name,
        'workUser10Time': workUser10Time,
        'workUser11Name': workUser11Name,
        'workUser11Time': workUser11Time,
        'workUser12Name': workUser12Name,
        'workUser12Time': workUser12Time,
        'workUser13Name': workUser13Name,
        'workUser13Time': workUser13Time,
        'workUser14Name': workUser14Name,
        'workUser14Time': workUser14Time,
        'workUser15Name': workUser15Name,
        'workUser15Time': workUser15Time,
        'workUser16Name': workUser16Name,
        'workUser16Time': workUser16Time,
        'visitCount1_12': visitCount1_12,
        'visitCount1_20': visitCount1_20,
        'visitCount1_22': visitCount1_22,
        'visitCount2_12': visitCount2_12,
        'visitCount2_20': visitCount2_20,
        'visitCount2_22': visitCount2_22,
        'visitCount3_12': visitCount3_12,
        'visitCount3_20': visitCount3_20,
        'visitCount3_22': visitCount3_22,
        'visitCount4_12': visitCount4_12,
        'visitCount4_20': visitCount4_20,
        'visitCount4_22': visitCount4_22,
        'visitCount5_12': visitCount5_12,
        'visitCount5_20': visitCount5_20,
        'visitCount5_22': visitCount5_22,
        'visitCount6_12': visitCount6_12,
        'visitCount6_20': visitCount6_20,
        'visitCount6_22': visitCount6_22,
        'lockerUse': lockerUse,
        'lockerLost': lockerLost,
        'lockerRecovery': lockerRecovery,
        'event1': event1,
        'event2': event2,
        'marketing': marketing,
        'interview': interview,
        'openSquare': openSquare,
        'openSquareFee': openSquareFee,
        'openSquareStatus': openSquareStatus,
        'meeting': meeting,
        'mailCheck10Name': mailCheck10Name,
        'mailCheck10Status': mailCheck10Status,
        'mailCheck12Name': mailCheck12Name,
        'mailCheck12Status': mailCheck12Status,
        'mailCheck18Name': mailCheck18Name,
        'mailCheck18Status': mailCheck18Status,
        'mailCheck22Name': mailCheck22Name,
        'mailCheck22Status': mailCheck22Status,
        'warning19Status': warning19Status,
        'warning19Deal': warning19Deal,
        'warning23Status': warning23Status,
        'warning23Deal': warning23Deal,
        'advance1': advance1,
        'advance2': advance2,
        'advance3': advance3,
        'repair': repair,
        'repairStatus': repairStatus,
        'repairDeal': repairDeal,
        'problem': problem,
        'problemDeal': problemDeal,
        'pamphlet1Status': pamphlet1Status,
        'pamphlet1Name': pamphlet1Name,
        'pamphlet1Fee': pamphlet1Fee,
        'pamphlet2Status': pamphlet2Status,
        'pamphlet2Name': pamphlet2Name,
        'pamphlet2Fee': pamphlet2Fee,
        'pamphlet3Status': pamphlet3Status,
        'pamphlet3Name': pamphlet3Name,
        'pamphlet3Fee': pamphlet3Fee,
        'pamphlet4Status': pamphlet4Status,
        'pamphlet4Name': pamphlet4Name,
        'pamphlet4Fee': pamphlet4Fee,
        'pamphlet5Status': pamphlet5Status,
        'pamphlet5Name': pamphlet5Name,
        'pamphlet5Fee': pamphlet5Fee,
        'pamphlet6Status': pamphlet6Status,
        'pamphlet6Name': pamphlet6Name,
        'pamphlet6Fee': pamphlet6Fee,
        'pamphlet7Status': pamphlet7Status,
        'pamphlet7Name': pamphlet7Name,
        'pamphlet7Fee': pamphlet7Fee,
        'equipment1Type': equipment1Type,
        'equipment1Name': equipment1Name,
        'equipment1Vendor': equipment1Vendor,
        'equipment1Delivery': equipment1Delivery,
        'equipment1Client': equipment1Client,
        'equipment2Type': equipment2Type,
        'equipment2Name': equipment2Name,
        'equipment2Vendor': equipment2Vendor,
        'equipment2Delivery': equipment2Delivery,
        'equipment2Client': equipment2Client,
        'equipment3Type': equipment3Type,
        'equipment3Name': equipment3Name,
        'equipment3Vendor': equipment3Vendor,
        'equipment3Delivery': equipment3Delivery,
        'equipment3Client': equipment3Client,
        'equipment4Type': equipment4Type,
        'equipment4Name': equipment4Name,
        'equipment4Vendor': equipment4Vendor,
        'equipment4Delivery': equipment4Delivery,
        'equipment4Client': equipment4Client,
        'equipment5Type': equipment5Type,
        'equipment5Name': equipment5Name,
        'equipment5Vendor': equipment5Vendor,
        'equipment5Delivery': equipment5Delivery,
        'equipment5Client': equipment5Client,
        'equipment6Type': equipment6Type,
        'equipment6Name': equipment6Name,
        'equipment6Vendor': equipment6Vendor,
        'equipment6Delivery': equipment6Delivery,
        'equipment6Client': equipment6Client,
        'contact': contact,
        'lastConfirm': lastConfirm,
        'agenda': agenda,
        'confirm1': confirm1,
        'confirm2': confirm2,
        'confirm3': confirm3,
        'confirm4': confirm4,
        'confirm5': confirm5,
        'confirm6': confirm6,
        'confirm7': confirm7,
        'confirm8': confirm8,
        'confirm9': confirm9,
        'confirm10': confirm10,
        'confirm11': confirm11,
        'confirm12': confirm12,
        'passport': passport,
        'passportCount1': passportCount1,
        'passportCount2': passportCount2,
        'passportCount3': passportCount3,
        'createdUserId': loginUser.id,
        'createdUserName': loginUser.name,
      });
    } catch (e) {
      error = '日報の保存に失敗しました';
    }
    return error;
  }

  Future<String?> approval({
    required ReportModel report,
    required UserModel? loginUser,
  }) async {
    String? error;
    if (loginUser == null) return '日報の承認に失敗しました';
    try {
      _reportService.update({
        'id': report.id,
        'approval': 1,
      });
    } catch (e) {
      error = '日報の承認に失敗しました';
    }
    return error;
  }

  Future<String?> delete({
    required ReportModel report,
  }) async {
    String? error;
    try {
      _reportService.delete({
        'id': report.id,
      });
    } catch (e) {
      error = '日報の削除に失敗しました';
    }
    return error;
  }
}
